### ISSUE TITLE
Camera doesn't follow headset accurately

### ISSUE THREAD

**Issue by Sirvoid** [FireFlyForLife/rlOpenXR#1]
Built the demos using cmake and tested them on Quest 2 with link and airlink in 90hz and 120hz. The camera doesn't follow the headset accurately making me sick very quickly.
Tried also with virtual desktop and steamvr but it's even worst. The image is stuttering like crazy when moving my head but only in the hmd view.
I don't believe it is an issue on my end as I do pcvr using those everyday and everything works perfectly.

**Comment by FireFlyForLife** [comment]
Hi! Sorry to hear it's not working well with the quest and my delay to get back to you.

I only have a oculus rift myself. But I might be able to debug with a friend who has a quest 2.

In the meantime, could you try moving the `rlOpenXRUpdateCamera()` call to directly after `rlOpenXRBegin()`? the rlOpenXRBegin call is also responsible for waiting until the next frame (it's own VSync sort of) and updating the time which will be used by the rlOpenXRUpdateCamera call.

**Comment by Sirvoid** [comment]
> Hi! Sorry to hear it's not working well with the quest and my delay to get back to you.
> 
> I only have a oculus rift myself. But I might be able to debug with a friend who has a quest 2.
> 
> In the meantime, could you try moving the `rlOpenXRUpdateCamera()` call to directly after `rlOpenXRBegin()`? the rlOpenXRBegin call is also responsible for waiting until the next frame (it's own VSync sort of) and updating the time which will be used by the rlOpenXRUpdateCamera call.

Sorry for the late reply, I just tried it and it seems to be working, thanks!

**Comment by FireFlyForLife** [comment]
I've moved the `xrWaitFrame()` call from `rlOpenXRBegin()` to `rlOpenXRUpdate()`. According to the OpenXR documentation this makes sense to do. And fixes your issue in the process!
